#!/bin/sh
set -eu

: "${SKILLHUB_WEB_API_BASE_URL:=}"
: "${SKILLHUB_PUBLIC_BASE_URL:=}"
: "${SKILLHUB_WEB_AUTH_DIRECT_ENABLED:=}"
: "${SKILLHUB_WEB_AUTH_DIRECT_PROVIDER:=}"
: "${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_ENABLED:=}"
: "${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_PROVIDER:=}"
: "${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_AUTO:=}"
: "${SKILLHUB_WEB_AUTH_DINGTALK_ENABLED:=}"
: "${SKILLHUB_WEB_AUTH_DINGTALK_PROVIDER:=}"
: "${SKILLHUB_WEB_AUTH_DINGTALK_AUTO:=}"
: "${SKILLHUB_WEB_AUTH_DINGTALK_CORP_ID:=}"

envsubst '${SKILLHUB_WEB_API_BASE_URL} ${SKILLHUB_PUBLIC_BASE_URL} ${SKILLHUB_WEB_AUTH_DIRECT_ENABLED} ${SKILLHUB_WEB_AUTH_DIRECT_PROVIDER} ${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_ENABLED} ${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_PROVIDER} ${SKILLHUB_WEB_AUTH_SESSION_BOOTSTRAP_AUTO} ${SKILLHUB_WEB_AUTH_DINGTALK_ENABLED} ${SKILLHUB_WEB_AUTH_DINGTALK_PROVIDER} ${SKILLHUB_WEB_AUTH_DINGTALK_AUTO} ${SKILLHUB_WEB_AUTH_DINGTALK_CORP_ID}' \
  < /usr/share/nginx/html/runtime-config.js.template \
  > /usr/share/nginx/html/runtime-config.js
